#!/bin/bash
# Bash completion for chwal

_chwal_completions() {
	local cur prev opts
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD - 1]}"

	opts="-h --help -V --version -l --load -m --mark \
-d --dir --directory -p --pre --pre-hook -P --post --post-hook"

	case "$prev" in
		-d | --dir | --directory)
			COMPREPLY=($(compgen -d -- "$cur"))
			return 0
			;;
		-p | --pre | --pre-hook | -P | --post | --post-hook)
			COMPREPLY=($(compgen -f -- "$cur"))
			return 0
			;;
	esac

	COMPREPLY=($(compgen -W "${opts}" -- "$cur"))
	return 0
}

complete -F _chwal_completions chwal
